export const RUBRIC_DEFAULT_CRITERIA = [
  {
    id: "crit_mission",
    name: "Mission Relevance (Advaita Vedanta)",
    category: "NON_NEGOTIABLE",
    weight: 0.25,
    minThreshold: 0.85,
    description: "Aligns with core teachings of Bhagavad Gita, Upanishads, Sant Kabir, and self-enquiry.",
    evaluationRule: "Directly addresses core existential confusion, desire, or fear.",
    isVetoTrigger: true,
  },
  {
    id: "crit_meaning",
    name: "Meaning Preservation",
    category: "NON_NEGOTIABLE",
    weight: 0.25,
    minThreshold: 0.90,
    description: "No cut mid-argument; speaker premise and context preserved completely.",
    evaluationRule: "Complete thought intact from premise to resolution.",
    isVetoTrigger: true,
  },
  {
    id: "crit_content",
    name: "Content Quality & Argument Strength",
    category: "QUALITY",
    weight: 0.15,
    minThreshold: 0.70,
    description: "High intellectual rigor, logical coherence, and insightful refutation.",
    evaluationRule: "Clear logical premises and definitive spiritual conclusion.",
    isVetoTrigger: false,
  },
  {
    id: "crit_audience",
    name: "Audience & Seeker Relevance",
    category: "ENGAGEMENT",
    weight: 0.15,
    minThreshold: 0.65,
    description: "Speaks to real-world corporate stress, youth confusion, relationship attachments.",
    evaluationRule: "Pragmatic application of timeless wisdom to modern struggle.",
    isVetoTrigger: false,
  },
  {
    id: "crit_novelty",
    name: "Novelty & Unique Insight",
    category: "QUALITY",
    weight: 0.10,
    minThreshold: 0.60,
    description: "Fresh metaphors, unexpected angles, or unique scriptural interpretation.",
    evaluationRule: "Distinct from common cliches.",
    isVetoTrigger: false,
  },
  {
    id: "crit_ethics",
    name: "Ethical & Editorial Compliance",
    category: "NON_NEGOTIABLE",
    weight: 0.10,
    minThreshold: 0.95,
    description: "No sensationalist clickbait, no distortion of seeker intent.",
    evaluationRule: "Adheres strictly to AP ethical communication principles.",
    isVetoTrigger: true,
  },
] as const;

export const SUPPORTED_VIDEO_FORMATS = [
  "video/mp4",
  "video/quicktime",
  "video/x-matroska",
  "video/webm",
] as const;
